src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/domain/CaseTransformationResponse.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/transformers/CaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/RPE-744
- Added transformation résponse wrapper
- Added/updated unit tests
```
[ ] Yes
[ x] No
```
=> Added transformation response wrapper and updated tests

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelper.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelperTest.java
https://tools.hmcts.net/jira/browse/RPE-744
- Added helper to create case in CCD
- Added unit tests
- Please note that I have added unit tests for only few basic scenario. I think it will be worth adding all the scenarios such as Invalid case type, jurisdiction, event type , invalid user/service authorisation tokens etc as part of functional tests as currently for unit tests everything is mocked.But happy to add those if reviewer thinks it's worth.
```
[ ] Yes
[x ] No
```
=> Add create case ccd interface

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/common/SampleCaseDataCreator.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/RPE-744
-  More tests related to CCD to be added in integration PR
```
[ ] Yes
[x ] No
```
=> Integrate handler case helper

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/domain/CaseDetails.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/domain/ExceptionCaseData.java
- Jackson needs constructors for creating exception record and case details object.
```
[ ] Yes
[x ] No
```
=> Added lombok annotation for no arg and all arg constructors

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4230
- If 2 booleans contradict each other, then add an error to the error list
- If the boolean value is text then add an error to the error list
```
[ ] Yes
[x ] No
```
=> SSCS-4230 Handle contradicting booleans

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4231
- When a date is in an invalid format then add an error to the list
```
[ ] Yes
[X ] No
```
=> SSCS-4231 Handle invalid dates

src/integrationTest/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelperTest.java, src/integrationTest/resources/application.yaml, src/main/java/uk/gov/hmcts/reform/sscs/auth/AuthService.java, src/main/java/uk/gov/hmcts/reform/sscs/config/AuthServiceConfig.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptionhandlers/ResponseExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/ForbiddenException.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/UnAuthorizedException.java, src/main/java/uk/gov/hmcts/reform/sscs/exceptions/UnauthorizedException.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/auth/AuthServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java
https://tools.hmcts.net/jira/browse/RPE-773
-  Added auth service to validate service token and check if service is allowed to handle callback
- Added unit tests
```
[ ] Yes
[x ] No
```
=> Integrated s2s to validate service token and added tests

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtilTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4242
- Appointee data should be mapped to the correct fields in CCD
```
[ ] Yes
[X] No
```
=> SSCS-4242 Handle appointee data

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/SSCS-4084
This change implements mutation testing using Pitest, including:
- setup Pitest in build.gradle
- set success threshold
- add mutation testing to build pipeline (while tests don't take too long)
- add mutation testing to overnight pipeline for safety net if build step removed in future
```
[x] Yes (in that the build will break)
[ ] No
```
=> SSCS-4084 implemented mutation testing

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4275
- Update the references for some of the OCR fields to bring into line with Exela
```
[ ] Yes
[X ] No
```
=> Sscs 4275 update ocr id references

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtilTest.java
SSCS-4230 Correctly handle booleans that contradict
=> SSCS-4230 Correctly handle booleans that contradict

src/integrationTest/resources/mappings/case-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/json/SscsJsonExtractor.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/json/SscsJsonExtractorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtilTest.java
https://tools.hmcts.net/jira/browse/SSCS-4235
- Correctly handle sign languages and default to British Sign Language if it can't be found
- Correctly handle hearing arrangements
```
[ ] Yes
[ x] No
```
=> Sscs 4235 handle sign languages

src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
SSCS-4235 append dialect to language type
=> SSCS-4235 append dialect to language type

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json
=> Increase common library to 0.0.117

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-incomplete-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4359
- When no mrn date then show a warning to the caseworker
- When mrn date is present the add it to the MrnDetails object in the transformer
```
[ ] Yes
[x ] No
```
=> SSCS-4359 Show warning if no MRN date

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4360
- When the Mrn date for a case is greater than 13 months, send it to interlocutory review state
```
[ ] Yes
[ x] No
```
=> SSCS-4360 Interlocutory review cases

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4344
- When excluded date has a single date range add to start of ExcludedDate object
- When excluded date has a date range add to start and end of ExcludedDate object
- When excluded date contains invalid date text then show an error
```
[ ] Yes
[ x] No
```
=> SSCS-4344 Handle excluded dates

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/transformers/CaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4396
Add bulk scan case reference to SSCS transformed case
```
[ ] Yes
[ x] No
```
=> SSCS-4396 Add bulk scan case reference to SSCS transformed case

build.gradle, config/owasp/suppressions.xml, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4409
- Add receivedVia paper to transformation
```
[ ] Yes
[x ] No
```
=> SSCS-4409 Add receivedVia paper to transformation

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4423
Set case created date for case
```
[ ] Yes
[ x] No
```
=> SSCS-4423 Set case created date

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackControllerTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4479
- Check for valid benefit type
- If empty, then show a warning
- If invalid, then show an error
```
[ ] Yes
[x ] No
```
=> SSCS-4479 Benefit type errors and warnings

build.gradle, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
- Set benefit type description if valid benefit code
=> SSCS-4479 set benefit type description

src/test/resources/import/all_fields_entered.json, src/test/resources/import/mrn_date_greater_than_13_months.json, src/test/resources/import/some_mandatory_fields_missing.json
Update test data to use correct benefit type codes (acronyms rather than full text descriptions)
```
[ ] Yes
[x] No
```
=> Update test data to use correct benefit type codes

src/main/java/uk/gov/hmcts/reform/sscs/exceptions/CaseDataHelperException.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-3672
Wrap all exceptions from CCD create case call in a custom exception, and throw.
```
[ ] Yes
[x] No
```
=> Sscs 3672 ccd exception handling

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanCallbackIntegrationTest.java, src/integrationTest/resources/mappings/case-creation-request.json, src/integrationTest/resources/mappings/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4354
- Find regional processing center for case based on postcode
```
[ ] Yes
[ x] No
```
=> SSCS-4354 Find RPC for postcode

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-and-appointee-request.json, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4598
Sscs 4598 appointee validation
```
[ ] Yes
[x ] No
```
=> Sscs 4598 appointee validation

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/integrationTest/resources/mappings/validation/validate-appeal-created-case-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-and-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-interloc-appeal-created-case-request.json, src/test/resources/import/all_fields_entered.json, src/test/resources/import/mrn_date_greater_than_13_months.json, src/test/resources/import/some_mandatory_fields_missing.json
https://tools.hmcts.net/jira/browse/SSCS-4579
- When a interlocValidAppeal event is received then validate and send case to robotics
```
[ ] Yes
[x ] No
```
=> SSCS-4579 Interloc case to robotics

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java, src/functionalTest/resources/import/validate_appeal_created_case_request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-case-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-and-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-representative-request.json, src/integrationTest/resources/mappings/validation/validate-interloc-appeal-created-case-request.json
https://tools.hmcts.net/jira/browse/SSCS-4397
Add interloc and validate appeal functional tests
```
[ ] Yes
[ x] No
```
=> Add interloc and validate appeal functional tests

Dockerfile, Jenkinsfile_CNP, kubernetes/config.aat.yaml, kubernetes/config.saat.yaml, kubernetes/deployment.template.yaml
https://tools.hmcts.net/jira/browse/SSCS-4541
Initial configuration to deploy to AKS in the pipeline.
```
[ ] Yes
[x] No
```
=> Initial config for AKS

Jenkinsfile_CNP, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4701
Feature flag Robotics
```
[ ] Yes
[x ] No
```
=> SSCS-4701 Feature flag Robotics

src/functionalTest/resources/import/some_mandatory_fields_missing.json, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-request.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/CallbackType.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4636
- Given a case comes from SSCS to validate then swap warning messages appropriately
```
[ ] Yes
[ x] No
```
=> SSCS-4636 Warning message mappings

src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/smokeTest/java/uk/gov/hmcts/reform/sscs/GetSmokeCase.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtilTest.java
https://tools.hmcts.net/jira/browse/SSCS-4821
- Warning now shown whenever an invalid date is entered
```
[ ] Yes
[x ] No
```
=> SSCS-4821 Invalid dates bug

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4657
Add generated fields for validated case types
```
[ ] Yes
[ x] No
```
=> SSCS-4657 Add generated fields for validated case types

src/functionalTest/resources/import/all_fields_entered.json, src/functionalTest/resources/import/mrn_date_greater_than_13_months.json, src/functionalTest/resources/import/some_mandatory_fields_missing.json, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/integrationTest/resources/mappings/exception/case-creation-request.json, src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-request.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4710
- Add a warning message when Hearing Options Excluded Date is in the past
```
[ ] Yes
[ x] No
```
=> SSCS-4710 Warning for past excluded date

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java
https://tools.hmcts.net/jira/browse/SSCS-4091
```
[ ] Yes
[x] No
```
=> Additional logging information

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4885
```
[ ] Yes
[x] No
```
=> Make title a mandatory field

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/resources/mappings/exception/case-creation-request.json, src/integrationTest/resources/mappings/exception/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-4629
- Generate a TYA number so users can track their appeal 
```
[ ] Yes
[ x] No
```
=> SSCS-4629 Generate tya number

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-representative-request.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-4958
Add warning when rep name and organisation are not entered
```
[ ] Yes
[x ] No
```
=> SSCS-4958 Add warning when rep name and organisation are not entered

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-5005
SSCS-5005 Show warning when only rep title is entered
```
[ ] Yes
[x ] No
```
=>  SSCS-5005 Show warning when only rep title is entered

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-5126
=> SSCS-5126 Show error for unknown file extension

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java
=> common library upgrade

infrastructure/main.tf
Reference: hmcts/send-letter-service#327
```
[ ] Yes
[x] No
```
=> Derive ase_name from core compute environment

Jenkinsfile_CNP, config/owasp/suppressions.xml, infrastructure/aat.tfvars, kubernetes/config.aat.yaml
=> point bulk scan to SIDAM in AAT and AKS

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-5499
Add SSCS1 as doc subtype
```
[ ] Yes
[x ] No
```
=> SSCS-5499 Add SSCS1 as doc subtype

Jenkinsfile_CNP, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/helper/TestConstants.java, src/integrationTest/resources/mappings/exception/case-creation-request.json, src/integrationTest/resources/mappings/exception/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json, src/integrationTest/resources/mappings/update-case-request.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
- Send case to dwp once robotics has completed
- Put behind feature flag
=> Sscs 5559 send to dwp

Jenkinsfile_CNP, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/output.tf, infrastructure/preview.tfvars, infrastructure/prod.tfvars, infrastructure/variables.tf, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/helper/TestConstants.java, src/integrationTest/resources/mappings/exception/case-creation-request.json, src/integrationTest/resources/mappings/exception/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json, src/integrationTest/resources/mappings/update-case-request.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsRoboticsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-5559
- Send case to dwp once robotics has completed
- Put behind feature flag
```
[ ] Yes
[x ] No
```
=> SSCS-5559 Send to dwp

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-5693
- Move robotics code to evidence share if feature flag on
```
[ ] Yes
[x ] No
```
=> SSCS-5693 Move robotics code to evidence share if feature flag on

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/helper/TestConstants.java, src/integrationTest/resources/mappings/exception/valid-appeal-request.json, src/integrationTest/resources/mappings/update-case-request.json, src/main/java/uk/gov/hmcts/reform/sscs/domain/CaseEvent.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
https://tools.hmcts.net/jira/browse/SSCS-5795
=> SSCS-5795 Create case in valid appeal state when feature flag enabled

build.gradle
=> SSCS-5911 - Could not deserialize callback

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-5989
Update sscs-common to include new venues file
```
[ ] Yes
[X] No
```
=> SSCS-5989 - update sscs-common version

build.gradle, infrastructure/main.tf, infrastructure/variables.tf, src/main/resources/application.yaml
turn on
```
[ ] Yes
[ ] No
```
=> upgrade common libraries to use the rpc email

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/SscsBulkScanFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-5722
Normalise nino
```
[ ] Yes
[X] No
```
=> SSCS-5722 - Normalise nino

charts/sscs-bulk-scan/Chart.yaml, charts/sscs-bulk-scan/values.preview.template.yaml, charts/sscs-bulk-scan/values.yaml
- Create a values.yaml file with default values
- values.preview.template.yaml is for PR's
=> fix helm charts

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/domain/ScannedRecord.java, src/test/java/uk/gov/hmcts/reform/sscs/json/SscsJsonExtractorTest.java
https://tools.hmcts.net/jira/browse/SSCS-6030
Ignore unknown properties
```
[ ] Yes
[X] No
```
=> SSCS-6030 - ignore unknown properties

src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-5996
Adding Worthing DRT as an ESA office
```
[ ] Yes
[X] No
```
=> SSCS-5996 - add dwp office

infrastructure/prod.tfvars
=> turn on send to Dwp

infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
=> extra logging in AAT

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-5963
Ignore empty hearing dates
```
[ ] Yes
[X] No
```
=> SSCS-5963 - update sscs-robotics-common version

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-4067
Update sscs-common rc version
```
[ ] Yes
[X] No
```
=> SSCS-4067 - update sscs-common rc version

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-6161
Fix build pipeline issue
```
[ ] Yes
[X] No
```
=> SSCS-6161 - fix build pipeline issue

Jenkinsfile_CNP, src/functionalTest/resources/import/all_fields_entered.json
https://tools.hmcts.net/jira/browse/SSCS-6378
=> remove deprecated config

config/owasp/suppressions.xml, src/functionalTest/resources/import/all_fields_entered.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtilTest.java
https://tools.hmcts.net/jira/browse/SSCS-6341
=> SSCS-6341 Allow caseworkers to enter yes, no, true, false in boolean fields

build.gradle, config/owasp/suppressions.xml
=> SSCS-6454: upgrade common lib

config/owasp/suppressions.xml
suppress CVE-2019-17531 till the end of the month
=> SSCS-6669 - suppress CVE-2019-17531 till the end of the month

build.gradle, config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/controllers/CcdCallbackController.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6839
=> SSCS-6839 Clear interloc review state

build.gradle, charts/sscs-bulk-scan/Chart.yaml
https://github.com/hmcts/sscs-evidence-share/pull/374
=> SSCS-6836 Add missing fields to java model

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
https://tools.hmcts.net/jira/browse/SSCS-6977
=> SSCS-6977 Set created in gaps for incomplete cases

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7131
=> SSCS-7131 Set DWP Regional Centre to work with filters

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7148
=> SSCS-7148 Set dwp regional center for ESA cases

Jenkinsfile_CNP, build.gradle, charts/sscs-bulk-scan/values.preview.template.yaml, config/checkstyle/checkstyle.xml, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-7270
=> SSCS-7270 Fix for document name extension validation issue

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/resources/schema/sscs-bulk-scan-schema.json, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7251
=> SSCS-7251 Tell tribunals about dates field with warning

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/validators/CaseValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/service/bulkscan/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-7320
=> SSCS-7320 Pass warning messages to validation service from transformation service

src/main/java/uk/gov/hmcts/reform/sscs/domain/ExactMatchList.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/FuzzyMatchList.java, src/main/java/uk/gov/hmcts/reform/sscs/service/FuzzyMatcherService.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/service/FuzzyMatcherServiceTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6344
=> SSCS-6344 Implement fuzzy matching for benefit type

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7335
=> SSCS-7335 Fix long titles for new SSCS1 PE form

infrastructure/aat.tfvars, infrastructure/prod.tfvars
=> adding back MI object ids

src/main/java/uk/gov/hmcts/reform/sscs/constants/WarningMessage.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-7336
=> SSCS-7336 Display error when invalid mobile number

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7338
=> SSCS-7338 Handle SSCS1PE form type as SSCS1 document type

src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-6910
=> SSCS-6910 Validate appellant postcode

src/integrationTest/resources/mappings/exception/case-creation-request.json, src/integrationTest/resources/mappings/exception/case-incomplete-creation-request.json, src/integrationTest/resources/mappings/exception/case-non-compliant-creation-request.json, src/integrationTest/resources/mappings/exception/valid-appeal-request.json, src/integrationTest/resources/mappings/update-case-request.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-6961
=> SSCS-6961 Store CCD office

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7382
=> SSCS-7382 Use nino for associating cases

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7389
=> Sscs 7389 find ae office without brackets

README.md, build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallbackOld.java, src/integrationTest/resources/mappings/exception/valid-appeal-response.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-7474
=> SSCS-7474 Duplication check for strategic bulk scan

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/BPS-1241
The change is applied in master not in the demo.
```
[ ] Yes
[x] No
```
=> Add Bulk scan processor to the allowed services list

src/main/resources/application.yaml
Whitelist `bulk_scan_orchesatrator` service to allow calling case transformation endpooint.
```
[ ] Yes
[x] No
```
=> Add Bulk scan orchestrator service to the allowed services list

build.gradle
=> SSCS-7550: New AirLookup

.github/renovate.json, build.gradle, charts/sscs-bulk-scan/Chart.yaml, charts/sscs-bulk-scan/requirements.yaml
SSCS-7587 - Upgrade java chart. Add renovate
=> SSCS-7587 - Upgrade java chart. Add renovate

build.gradle, src/main/resources/application.yaml
Add the service name sscs to the allowed services since sscs-tribunals-api will now calls sscs-bulk-scan.
=> SSCS-7730 - CCD UI – Have directionIssued validate prior to submitting the event

Dockerfile, build.gradle
SSCS-7703 - Upgrading to Java 11 - Bulk Scan
=> SSCS-7703 - Upgrading to Java 11 - Bulk Scan

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/main.tf, infrastructure/prod.tfvars
=> Updated new MI for demo env

infrastructure/main.tf
=> Updated azurerm version

security.sh
=> fixed the proxy error

src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
SSCS-7774 - Bulk scan/Validation – Rep name details blocks validation
=> SSCS-7774 - Bulk scan/Validation – Rep name details blocks validation

build.gradle
SSCS-7806 - Processing documents for reinstatement requests
=> SSCS-7806 - Processing documents for reinstatement requests

src/main/java/uk/gov/hmcts/reform/sscs/domain/FormType.java
Add another form type for SSCS1PEU
=> Add another form type for SSCS1PEU

infrastructure/main.tf, infrastructure/variables.tf
=> SSCS-8161: Tech debt – Fix bulk scan AppInsights

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/integrationTest/resources/mappings/ocr-validation/valid-ocr-data-for-uc.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
=> SSCS-8191: Office - UC bulk scan validation

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallbackOld.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTestOld.java
https://tools.hmcts.net/jira/browse/SSCS-8219
Changed warning message
```
[ ] Yes
[x] No
```
=> SSCS 8219 date warning message

config/owasp/suppressions.xml
=> Supress tomcat package

src/main/resources/application.yaml
=> SSCS-8133 - Enable UC locally

src/integrationTest/resources/mappings/ocr-validation/valid-ocr-data-for-uc.json, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
=> SSCS-8349: Bulkscan – UC office blank then should not throw warning

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallbackOld.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/helper/TestConstants.java, src/integrationTest/resources/mappings/existing-case-details-200-response.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/ccd/CaseDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/handler/SscsCaseDataHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-8330
=> SSCS-8330 Move to Elastic Search

src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
=> SSCS-8217 Address Validation

config/owasp/suppressions.xml
Fixing for nightly builds
```
[ ] Yes
[x] No
```
=> Suppress for nightly builds

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/validators/CaseValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTestOld.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTestOld.java
=> Sscs 8136 no mrn date or office

build.gradle
=> SSCS-7789 common update

build.gradle
=> Upgrade groovy

src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
SSCS-8449 - default all SYA cases to be created with digital = 'Yes'
=> SSCS-8449 - default all SYA cases to be created with digital = 'Yes'

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java
SSCS-8464: Upgrade Idam Client only
=> SSCS-8464: Upgrade Idam Client only

build.gradle
fix cve
```
[ ] Yes
[x] No
```
=> CVE-2021-22112

build.gradle
=> Fix dependency check

build.gradle
=> upgraded tomcat version to fix dependency check

Jenkinsfile_parameterized, build.gradle
=> SSCS-8864: Following tests are failing on bulk-scan nightly build

infrastructure/main.tf
Up azure version
```
[ ] Yes
[x] No
```
=> fix cnp azure version

Jenkinsfile_nightly, Jenkinsfile_parameterized
=> SSCS-8999: Fix Functional tests on bulk-scan nightly build

build.gradle, src/functionalTest/resources/validationsscs/validate_sscs_case_request.json, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanValidateRecordCallback.java, src/integrationTest/resources/mappings/validation/auto-validate-appeal-created-missing-appellant-and-appointee-request.json, src/integrationTest/resources/mappings/validation/auto-validate-appeal-created-missing-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-case-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-and-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appellant-request.json, src/integrationTest/resources/mappings/validation/validate-appeal-created-missing-appointee-request.json, src/integrationTest/resources/mappings/validation/validate-interloc-appeal-created-case-request.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
SSCS-8513 - Validating a case where “Has representative” is blank
=> SSCS-8513 - Validating a case where “Has representative” is blank

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java
Fix for sonar https://sonarcloud.io/dashboard?id=sscs-bulk-scan
=> SSCS-8513 - sonar fix

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9037
```
[ ] Yes
[ ] No
```
=> SSCS-9037: Review how RPCs is calculated via the Airlookup file

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9031
=> SSCS-9031 Carers allowance camel case fix

src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsKeyValuePairValidator.java
=> SSCS-9100: Investigate Fortify vulnerabilities

build.gradle, charts/sscs-bulk-scan/Chart.yaml
SSCS-8900 - Attendance Allowance - Airlookup, DWP addresses & Robot Configuration
=> SSCS-8900 - Attendance Allowance - Airlookup, DWP addresses & Robot Configuration

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java, src/functionalTest/resources/exception/all_fields_entered.json, src/functionalTest/resources/exception/all_fields_entered_uc.json, src/functionalTest/resources/exception/output/expected_all_fields_entered.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/valid-appeal-response.json
https://www.whitesourcesoftware.com/vulnerability-database/CVE-2020-7791
=> Suppress false positive CVE-2020-7791 since it is a C# CVE

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9066
Finished move to jitpack
```
[ ] Yes
[x] No
```
=> sscs 9066 removed bintray moved to jitpack refs

audit.json, build.gradle
=> Suppress low warnings, ticket raised to fixed this

src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
=> Fixed fortify issue

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-8906
=> SSCS-8906 Bereavement benefit DWP mappings

src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
https://tools.hmcts.net/jira/browse/SSCS-9184
```
[ ] Yes
[ x] No
```
=> SSCS-9184:Validate appeal

build.gradle
SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event
=> SSCS-9041 - CCD UI – Validate DWP originating and presenting office for the 'Response reviewed' event

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java
updated common with social fund benefit type.
Jira Ticket: [https://tools.hmcts.net/jira/browse/SSCS-9061](url)
=> SSCS - 9061 - Added social fund benefit type

build.gradle
=> Fixed spring release version

build.gradle, src/integrationTest/resources/application_it.yaml, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-9444
Added feature flag for UC default office
```
[ ] Yes
[x ] No
```
=> SSCS-9444- UC default dwp office feature flag

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9450
=> Sscs 9450 regional centre rfe

src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9460
Fix for a null pointer
```
[ ] Yes
[x] No
```
=> sscs 9460 added check for null and test

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9459
=> SSCS-9459 Update income support rfe mapping

src/functionalTest/resources/exception/all_fields_entered_uc.json
https://tools.hmcts.net/jira/browse/SSCS-9470
fix test
```
[ ] Yes
[x] No
```
=> sscs 9470 fix test data

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
SSCS-9341 - BenefitType not found
=> SSCS-9341 - BenefitType not found

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SSCS-9381
The changes are in this PR but the same are implemented on nightly branch
```
[ ] Yes
[ x] No
```
=> SSCS-9381:Enable fortify scan for nightly build

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java, src/functionalTest/resources/exception/all_fields_pip_office_entered_aa.json, src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtil.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/util/SscsOcrDataUtilTest.java
=> SSCS-9505: PIP Benefit - PIP DWP addresses marked as 'invalid office'

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
SSCS-9508 - BSPS - dwpAddress JSON #2261
=> SSCS-9508 - BSPS - dwpAddress JSON

infrastructure/main.tf
=> Updated provider version

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9437
```
[ ] Yes
[ ] No
```
=> SSCS-9437 Bulk scan – Upgrade org.springframework to v5.3.9

build.gradle
Reverts hmcts/sscs-bulk-scan#1044
=> Revert "SSCS-9437 Bulk scan – Upgrade org.springframework to v5.3.9"

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-9562
Bulk Scan: Add SSCS2 as a new Bulk Scan Form
```
[ ] Yes
[ x] No
```
=> SSCS-9562 Added SSCS2 handling

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationControllerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
Reverts hmcts/sscs-bulk-scan#1051
=> Revert "SSCS-9562 Added SSCS2 handling"

build.gradle, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9429
=> SSCS-9429 Deserialize case type id

config/owasp/suppressions.xml
=> Suppress Spring dependacy check until version is upgraded to 5.3.12

build.gradle
=> Fix unit tests

src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-9802
Bulk Scan: SSCS2 Form - Section 1
```
[ ] Yes
[x ] No
```
=> Sscs 9802 sscs2 form status

build.gradle
=> SSCS-9777: Tribunals / Common – Change the document ordering

src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9912
=> SSCS-9912 Update dwp issuing office location for sscs2

config/owasp/suppressions.xml
=> Extend suppression

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
=> SSCS-9904:Location data – Populate location data on creation bulk scan

build.gradle, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
=> SSCS-9904: Location data – Populate location data on creation bulk scan

src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java, src/functionalTest/resources/exception/output/expected_all_fields_auto_office_ma.json, src/functionalTest/resources/exception/output/expected_all_fields_entered.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_aa.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json, src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json, src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months.json, src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months_grounds_missing.json, src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json, src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json, src/functionalTest/resources/exception/output/sscs5_expected_all_fields_entered.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/case-incomplete-response.json, src/integrationTest/resources/mappings/exception/case-non-compliant-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/valid-appeal-response.json, src/integrationTest/resources/mappings/ocr-validation/sscs5-valid-ocr-data.json, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/domain/transformation/SuccessfulTransformationResponse.java, src/test/java/uk/gov/hmcts/reform/sscs/controllers/TransformationControllerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9970
=> SSCS-9970 Set HmctsServiceId in supplementary data

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
https://tools.hmcts.net/jira/browse/SSCS-9909
handle blank benefit type
```
[ ] Yes
[x] No
```
=> sscs 9909 handle blank benefit types

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10128
```
[ ] Yes
[X] No
```
=> Surpress dependency issues

build.gradle, src/functionalTest/resources/exception/output/expected_all_fields_auto_office_ma.json, src/functionalTest/resources/exception/output/expected_all_fields_entered.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_aa.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json, src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json, src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months.json, src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months_grounds_missing.json, src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json, src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json, src/functionalTest/resources/exception/output/sscs5_expected_all_fields_entered.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/case-incomplete-response.json, src/integrationTest/resources/mappings/exception/case-non-compliant-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/valid-appeal-response.json, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
https://tools.hmcts.net/jira/browse/SSCS-10070
Change data in 'caseAccessCategory' field from human readable to camelcase
```
[ ] Yes
[ ] No
```
=> SSCS - 10070 - Change data in 'caseAccessCategory' field

build.gradle
=> upgrading Log4j to 2.17.1

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10234
suppression date is updated
```
[X] Yes
[ ] No
```
=> SSCS-10234-suppressed till the beginning of april

build.gradle
=> SSCS-9872-update-commons-version

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10280
```
[ ] Yes
[X] No
```
=> SSCS-10280: suppressing dependencies

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10318
```
[ ] Yes
[x] No
```
=> SSCS-10318: update commons and POI

charts/sscs-bulk-scan/Chart.yaml, charts/sscs-bulk-scan/values.yaml, src/functionalTest/resources/exception/output/expected_all_fields_auto_office_ma.json, src/functionalTest/resources/exception/output/expected_all_fields_entered.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_aa.json, src/functionalTest/resources/exception/output/expected_all_fields_entered_uc.json, src/functionalTest/resources/exception/output/expected_all_fields_pip_office_entered_aa.json, src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months.json, src/functionalTest/resources/exception/output/expected_mrn_date_greater_than_13_months_grounds_missing.json, src/functionalTest/resources/exception/output/expected_some_mandatory_fields_missing.json, src/functionalTest/resources/exception/output/sscs2_expected_all_fields_entered.json, src/functionalTest/resources/exception/output/sscs5_expected_all_fields_entered.json, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/OcrValidationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/main/java/uk/gov/hmcts/reform/sscs/BulkScanApplication.java, src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/sscs/TestDataConstants.java, src/test/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandlerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-9902
```
[ ] Yes
[ ] No
```
=> SSCS-9902: Location data – Update airlookup to v15

Jenkinsfile_nightly
SSCS-9902
Turn on work allocation feature flag
```
[ ] Yes
[x] No
```
=> sscs 9902 added feature flag

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10444
```
[ ] Yes
[X] No
```
=> SSCS-10444 Change CVE Reporting

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/SSCS-10443
tagging added to Azure resources.
```
[ ] Yes
[X] No
```
=> Azure tagging

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10503
```
[ ] Yes
[X] No
```
=> suppressing dependency

config/owasp/suppressions.xml
=> SSCS-10533: Supress CVE-2016-1000027

Jenkinsfile_nightly
=> SSCS-10490 fix feature flag for nightly builds

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10552
```
[ ] Yes
[X] No
```
=> SSCS-10552: Upgrading Tomcat

Jenkinsfile_nightly
=> Remove CAM nightly flag

src/main/java/uk/gov/hmcts/reform/sscs/bulkscancore/handlers/CcdCallbackHandler.java, src/main/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelper.java, src/test/java/uk/gov/hmcts/reform/sscs/helper/SscsDataHelperTest.java
https://tools.hmcts.net/jira/browse/SSCS-10517
- change mentions of work allocation to cam
- make the code better
**Does this PR introduce a breaking change?**
```
[ ] Yes
[ x ] No
```
=> SSCS-10517 change mentions of work allocation to cam

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
https://tools.hmcts.net/jira/browse/SSCS-10178
```
[ ] Yes
[x] No
```
=> SSCS-10178 Commons Bump

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java, src/functionalTest/resources/exception/all_fields_entered_form_type_other.json, src/functionalTest/resources/exception/all_fields_entered_invalid_form_type.json, src/functionalTest/resources/exception/all_fields_entered_no_form_type.json, src/functionalTest/resources/exception/all_fields_entered_ocr_form_type.json, src/functionalTest/resources/exception/sscs2_all_fields_entered_ocr-form_type.json, src/functionalTest/resources/exception/sscs5_all_fields_entered_ocr-form_type.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/FormTypeValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsKeyValuePairValidator.java, src/main/resources/schema/sscs-bulk-scan-schema.json, src/main/resources/schema/sscs2-bulk-scan-schema.json, src/main/resources/schema/sscs5-bulk-scan-schema.json, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/FromTypeValidatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsKeyValuePairValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-10255
Check new form_type ocr field if no FormType
```
[ ] Yes
[x] No
```
=> sscs 10255 get ocr form type

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java
https://tools.hmcts.net/jira/browse/SSCS-10706
```
[ ] Yes
[x] No
```
=> Cardiff commons bump

config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/TransformationFunctionalTest.java, src/functionalTest/resources/exception/all_fields_entered_form_type_other.json, src/functionalTest/resources/exception/all_fields_entered_invalid_form_type.json, src/functionalTest/resources/exception/all_fields_entered_no_form_type.json, src/functionalTest/resources/exception/all_fields_entered_ocr_form_type.json, src/functionalTest/resources/exception/sscs2_all_fields_entered_ocr-form_type.json, src/functionalTest/resources/exception/sscs5_all_fields_entered_ocr-form_type.json, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/FormTypeValidator.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsKeyValuePairValidator.java, src/main/resources/schema/sscs-bulk-scan-schema.json, src/main/resources/schema/sscs2-bulk-scan-schema.json, src/main/resources/schema/sscs5-bulk-scan-schema.json, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/FromTypeValidatorTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsKeyValuePairValidatorTest.java
https://tools.hmcts.net/jira/browse/SSCS-10255
```
[ ] Yes
[ ] No
```
=> Sscs 10255 form type -restore

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10746
```
[ ] Yes
[ ] No
```
=> SSCS-10746-cve-fix

charts/sscs-bulk-scan/Chart.yaml
sscsBaseChartUpdate-Java401
```
[ ] Yes
[ ] No
```
=> sscsBaseChartUpdate-Java401

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10805
```
[ ] Yes
[ ] No
```
=> SSCS-10805-extend-suppression-date

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10805
```
[ ] Yes
[ ] No
```
=> SSCS-10805- update-jar-version

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-9874
```
[ ] Yes
[ ] No
```
=> SSCS-9874-common-version-update

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
https://tools.hmcts.net/jira/browse/SSCS-10841
=> SSCS-10841 Use epims ID to resolve court venue.

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Reverts hmcts/sscs-bulk-scan#1305
=> Revert "SSCS-10841 Use epims ID to resolve court venue."

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/main/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationService.java, src/test/java/uk/gov/hmcts/reform/sscs/service/CaseManagementLocationServiceTest.java
Reverts hmcts/sscs-bulk-scan#1311
=> Revert "Feature/sscs 10841 use epims id court venue"

build.gradle
=> SSCS-10841 Revert common change

build.gradle
https://tools.hmcts.net/jira/browse/SSCS-10818
```
[ ] Yes
[x] No
```
=> SSCS-10818 Commons Bump

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/BaseFunctionalTest.java, src/integrationTest/java/uk/gov/hmcts/reform/sscs/controllers/SscsBulkScanExceptionRecordCallback.java, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java
https://tools.hmcts.net/jira/browse/SSCS-10882
```
[ ] Yes
[x] No
```
=> SSCS-10882 Fixing Conflicting IDs

build.gradle, config/owasp/suppressions.xml
SSCS-10906
Update of snakeyaml library (was: suppression of not-applicable vulnerability)
```
[ ] Yes
[x] No
```
=> SSCS-10906 Long-term snakeyaml suppression

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCS-10985
```
[ ] Yes
[x] No
```
=> SSCS-10985 CVE Fix Commons Bump

.gitignore, infrastructure/main.tf
SSCS-11008
Add content type and tags to secrets
```
[ ] Yes
[ x ] No
```
=> SSCS-11008 - Add content type and tags

build.gradle, config/owasp/suppressions.xml
=> SSCS-11169 - upgrade jackson-databind

config/owasp/suppressions.xml
=> cve's suppression

config/git/pre-commit
=> SSCS-11165 : Updated windows variable

charts/sscs-bulk-scan/Chart.yaml, config/owasp/suppressions.xml
=> Supressions

audit.json
Removal Security Sh File
```
[ ] Yes
[x] No
```
=> RemovalSecurityShFile

audit.json
Security Scan Fix
```
[ ] Yes
[x] No
```
=> Security Scan Fix

config/owasp/suppressions.xml
=> suppress dependencies

build.gradle
CVEFix.30.05.2023 - Tomcat 9.0.75
```
[ ] Yes
[x] No
```
=> CVEFix.30.05.2023 - Tomcat 9.0.75

config/owasp/suppressions.xml
CVE Fix - 08.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 08.06.2023

config/owasp/suppressions.xml
CVE Fix - 27.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 27.06.2023

build.gradle
CVE Fix - 30.06.2023
```
[ ] Yes
[x] No
```
=> CVE Fix - 30.06.2023

build.gradle
CVE Fix 31.07.2023
```
[ ] Yes
[x] No
```
=> CVE Fix 31.07.2023

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/sscs-bulk-scan/Chart.yaml, charts/sscs-bulk-scan/values.yaml, infrastructure/main.tf, infrastructure/state.tf, lib/applicationinsights.json
=> Java 17 fix

lib/applicationinsights.json
Appinsights fix
```
[ ] Yes
[x] No
```
=> Appinsights fix

build.gradle
CVE Fix 04.08.2023
```
[ ] Yes
[x] No
```
=> CVEFix 04.08.2023

.github/renovate.json, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-12
Update renovate and suppressions
```
[ ] Yes
[X ] No
```
=> Update renovate and suppressions

config/owasp/suppressions.xml
=> SSCSCI-12: suppress CVEs

config/owasp/suppressions.xml
=> SSCS - Update supressions

README.md
https://tools.hmcts.net/jira/browse/SSCSCI-645
Update readme to trigger build
=> SSCSCI-645 - update readme

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-769
Updated sscs-common to 5.3.4
=> Updated sscs-common to 5.3.4

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-849
Updated suppression date.
```
[ ] Yes
[x] No
```
=> Suppression date fix

charts/sscs-bulk-scan/Chart.yaml, charts/sscs-bulk-scan/values.yaml
https://tools.hmcts.net/jira/browse/SSCSCI-499
```
[ ] Yes
[ ] No
```
=> SSCSCI-499: upgrade java chart

build.gradle, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/case-incomplete-response.json, src/integrationTest/resources/mappings/exception/case-non-compliant-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/valid-appeal-response.json
https://tools.hmcts.net/jira/browse/SSCSCI-933
update sscs-common
```
[ ] Yes
[ ] No
```
=> SSCSCI-933: update sscs-common

build.gradle, charts/sscs-bulk-scan/Chart.yaml, charts/sscs-bulk-scan/values.yaml, config/owasp/suppressions.xml, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response-attendance-allowance.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/auto-valid-appeal-with-appointee-response.json, src/integrationTest/resources/mappings/exception/case-incomplete-response.json, src/integrationTest/resources/mappings/exception/case-non-compliant-response.json, src/integrationTest/resources/mappings/exception/sscs2-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/sscs5-valid-appeal-response.json, src/integrationTest/resources/mappings/exception/valid-appeal-response.json
=> Nightly pipeline

build.gradle
- https://tools.hmcts.net/jira/browse/SSCSCI-923
- Upgrade sscs-common, update Reading venue address
```
[ ] Yes
[X] No
```
=> Upgrade sscs-common, update Reading venue address

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SSCSCI-1004
common version bump to update huddersfield venue address
```
[ ] Yes
[ ] No
```
=> SSCSCI-1004: update sscs-common to 5.11.8

audit.json, src/main/resources/application.yaml
See [SSCSCI-1385](https://tools.hmcts.net/jira/browse/SSCSCI-1385)
Updated path of api-docs.
=> SSCSCI-1385 security scan fix

lib/applicationinsights.json
=> Add sampling for health requests

Dockerfile
=> Upgrade app insights to latest

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/constants/SscsConstants.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java
https://tools.hmcts.net/jira/browse/SSCSCI-1128
Alter validation rules for IBCA cases.
Reason being that validation of appellant and representative data is being done in manual case create and update in ExUI for IBCA cases
=> SSCSCI-1128

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1185
=> Bump common to latest version(include enum changes for add hearing outcome)

build.gradle
See [SSCSCI-1406](https://tools.hmcts.net/jira/browse/SSCSCI-1406)
Fix for isIbcCase method to cover event of create case mid event
```
[ ] Yes
[ ] No
```
=> SSCSCI-1406-fix: bumping up commons

build.gradle, src/main/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformer.java, src/main/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidator.java, src/test/java/uk/gov/hmcts/reform/sscs/transformers/SscsCaseTransformerTest.java, src/test/java/uk/gov/hmcts/reform/sscs/validators/SscsCaseValidatorTest.java
=> SSCSCI-1214 commons bump to pr

build.gradle
https://tools.hmcts.net/jira/browse/SSCSSI-247
Update to sscs commons
```
[x ] Yes
[ ] No
```
=> SSCSSI-247: Update to sscs commons

build.gradle
=> SSCSCI-1347 commons bump

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1205
```
[ ] Yes
[ ] No
```
=> SSCSCI-1205: update sscs-common

build.gradle
=> SSCSCI-1531

build.gradle
Reverts hmcts/sscs-bulk-scan#1553
=> Revert "commons bump"

build.gradle
Reverts hmcts/sscs-bulk-scan#1554
=> Revert "Revert "commons bump""

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1605
sscs-common bump to 6.0.9
```
[ ] Yes
[ ] No
```
=> SSCSCI-1605 common bump

build.gradle
=> SSCSCI-1778

build.gradle
https://tools.hmcts.net/jira/browse/SSCSCI-1719
```
[ ] Yes
[ ] No
```
=> SSCSCI-1719 commons bump
